version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py wait_for_db && python manage.py test && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/testz1
    ports:
      - "8000:8000"
    depends_on:
      - db
