# Generated by Django 4.2.3 on 2023-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testz1', '0003_alter_user_id_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('protected', 'Protegida'), ('private', 'Privada')], default='public', max_length=20),
        ),
    ]
