# Generated by Django 4.2.3 on 2023-07-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testz1', '0004_idea_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', null=True, verbose_name='Fecha de creación'),
        ),
    ]
