# Generated by Django 4.2.3 on 2023-07-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testz1', '0009_alter_follow_follower_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='notification',
            name='leida',
            field=models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída por el usuario.', verbose_name='Leída'),
        ),
        migrations.AddField(
            model_name='notification',
            name='mensaje',
            field=models.TextField(default=1, help_text='Escribe el contenido del mensaje de la notificación.', verbose_name='Mensaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(help_text='Selecciona el usuario que está siguiendo a otro.', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(help_text='Selecciona el usuario que está siendo seguido.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Siguiendo'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('denied', 'Denegado')], default='pending', help_text='Selecciona el estado de la relación de seguimiento.', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(help_text='Selecciona el autor de la idea.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.CharField(help_text='Escribe el contenido de la idea (máximo 200 caracteres).', max_length=200, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('protected', 'Protegida'), ('private', 'Privada')], default='public', help_text='Selecciona la visibilidad de la idea.', max_length=20, verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó esta notificación.', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='idea',
            field=models.ForeignKey(help_text='Selecciona la idea relacionada con esta notificación.', on_delete=django.db.models.deletion.CASCADE, to='testz1.idea', verbose_name='Idea relacionada'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Selecciona el usuario al que se enviará esta notificación.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Introduce tu dirección de correo electrónico.', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es parte del personal o staff.', verbose_name='Es personal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Introduce tu nombre de usuario.', max_length=150, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
