# Generated by Django 4.2.3 on 2023-07-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testz1', '0010_alter_idea_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
    ]
